### ISSUE TITLE
invalid syntax (F999)

### ISSUE THREAD

**Issue by dmj619** [PRIS2/Fi#1]
En python las expresiones aritméticas se escriben con `and`, `or`...
#### Occurred on:
+ **Commit**:  19fad1b449ce71ec6ae6c5fed5e71dbe3fc90052
+ **File**:    [Monomio.py](https://github.com/PRIS2/Fi/blob/19fad1b449ce71ec6ae6c5fed5e71dbe3fc90052/Monomio.py)
+ **LineNum**: [16](https://github.com/PRIS2/Fi/blob/19fad1b449ce71ec6ae6c5fed5e71dbe3fc90052/Monomio.py#L16)
+ **Code**:    `return igualLiteral && terminosCompatiblesLiteral(self, other)`

    
#### Currently on:
+ **Commit**:  c578fc84a173513924ab503b41fba1272baf14d5
+ **File**:    [Monomio.py](https://github.com/PRIS2/Fi/blob/c578fc84a173513924ab503b41fba1272baf14d5/Monomio.py)
+ **LineNum**: [16](https://github.com/PRIS2/Fi/blob/c578fc84a173513924ab503b41fba1272baf14d5/Monomio.py#L16)

**Comment by Palla551** [comment]
Yo patrocino, este Issue.
